name: "archon GitHub Action"
description: "Run archon in GitHub Actions workflows"
branding:
  icon: "code"
  color: "orange"

inputs:
  model:
    description: "Model to use"
    required: true

  agent:
    description: "Agent to use. Must be a primary agent. Falls back to default_agent from config or 'build' if not found."
    required: false

  share:
    description: "Share the archon session (defaults to true for public repos)"
    required: false

  prompt:
    description: "Custom prompt to override the default prompt"
    required: false

  use_github_token:
    description: "Use GITHUB_TOKEN directly instead of Archon App token exchange. When true, skips OIDC and uses the GITHUB_TOKEN env var."
    required: false
    default: "false"

  mentions:
    description: "Comma-separated list of trigger phrases (case-insensitive). Defaults to '/archon,/ac'"
    required: false

  variant:
    description: "Model variant for provider-specific reasoning effort (e.g., high, max, minimal)"
    required: false

  oidc_base_url:
    description: "Base URL for OIDC token exchange API. Only required when running a custom GitHub App install."
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install root dependencies
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: bun install --frozen-lockfile

    - name: Build archon binary from source
      shell: bash
      working-directory: ${{ github.action_path }}/../packages/opencode
      run: bun run build --single --skip-install
      env:
        CI: "true"

    - name: Install archon binary to PATH
      shell: bash
      working-directory: ${{ github.action_path }}/../packages/opencode
      run: |
        mkdir -p "$HOME/.archon/bin"
        # Find the built binary (single build outputs for current platform)
        BINARY=$(find dist -name "opencode" -o -name "opencode.exe" 2>/dev/null | head -1)
        if [ -z "$BINARY" ]; then
          echo "ERROR: Built binary not found in dist/"
          ls -la dist/ || true
          exit 1
        fi
        cp "$BINARY" "$HOME/.archon/bin/archon"
        chmod +x "$HOME/.archon/bin/archon"
        echo "$HOME/.archon/bin" >> $GITHUB_PATH
        echo "Installed archon from $BINARY"

    - name: Run archon
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: bun run github/index.ts
      env:
        MODEL: ${{ inputs.model }}
        AGENT: ${{ inputs.agent }}
        SHARE: ${{ inputs.share }}
        PROMPT: ${{ inputs.prompt }}
        USE_GITHUB_TOKEN: ${{ inputs.use_github_token }}
        TOKEN: ${{ env.GITHUB_TOKEN }}
        MENTIONS: ${{ inputs.mentions }}
        VARIANT: ${{ inputs.variant }}
        OIDC_BASE_URL: ${{ inputs.oidc_base_url }}
